name: manimlib-creation
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy>=1.20.0
  - typing-extensions>=4.0.0
  - pip
  - pip:
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - pytest-xdist>=3.0.0
    - black>=22.0.0
    - isort>=5.10.0
    - flake8>=5.0.0
    - mypy>=1.0.0
    - build
    - twine
    - setuptools>=61.0
    - wheel