name: Quick Fix Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'creationbuild_package/environment.yml'

jobs:
  test-fix:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Miniconda with mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.10'
        channels: conda-forge,defaults
        environment-file: creationbuild_package/environment.yml
        activate-environment: manimlib-creation
        auto-activate-base: false
        use-mamba: true
        mamba-version: "*"

    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        which python
        python --version
        echo "Checking manimgl installation:"
        python -c "import manimgl; print(f'ManimGL version: {manimgl.__version__}')"

    - name: Test basic functionality
      shell: bash -l {0}
      timeout-minutes: 5
      run: |
        cd creationbuild_package
        python -c "import creation; creation._module_self_test()"
        echo "✅ Basic functionality test passed!"

    - name: Test import dependencies
      shell: bash -l {0}
      run: |
        python -c "import numpy; print(f'NumPy version: {numpy.__version__}')"
        python -c "import manimlib; print('ManimLib imported successfully')"
        echo "✅ All dependencies imported successfully!"